
package Formularios;

import Clases.ColaEnlazada;
import Clases.Dato;
import Clases.PilaEnlazada;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Formulario1 extends javax.swing.JFrame {
    
    ColaEnlazada cola;
    PilaEnlazada pila;
    Dato oDato;
    
    public Formulario1() {
        initComponents();
        setLocationRelativeTo(null);
        oDato = new Dato();
        cola = new ColaEnlazada();
        pila = new PilaEnlazada();
    }
    
    public void mostrarPilaEnlazada(JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
        
        if(!pila.pilaVacia()){
            int cont = pila.getTamaño();
            modelo.setRowCount(cont);
            PilaEnlazada aux = new PilaEnlazada();

            for(int i=0; i<cont; i++){
                oDato = (Dato) pila.pop();
                oDato.mostrarDatoPila(this.jTab_PilaDatos, i);
                aux.push(oDato);
            }

            while(!aux.pilaVacia())
                pila.push(aux.pop());
            }else
                JOptionPane.showMessageDialog(null, "La pila esta vacia!!!");
        
    }
    
    public void mostrarColaEnlazada(JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
        modelo.setColumnCount(cola.getTamaño()+1);
        modelo.setRowCount(3);
        
        this.jTab_ColaDatos.setValueAt("NUMERO", 0, 0);
        this.jTab_ColaDatos.setValueAt("NOMBRE", 1, 0);
        this.jTab_ColaDatos.setValueAt("COSTO", 2, 0);
        
        if(!cola.colaVacia()){
            Dato aux;
            
            for(int i=1; i<=cola.getTamaño(); i++){
                aux = (Dato) cola.eliminar();
                aux.mostrarDatoCola(this.jTab_ColaDatos, i);
                cola.insertar(aux);
            }
            
            
        }else
            JOptionPane.showMessageDialog(null, "La cola esta vacia!!!");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTab_DatoAleatorio = new javax.swing.JTable();
        jBut_DatoAleatorio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTab_PilaDatos = new javax.swing.JTable();
        jBut_Push = new javax.swing.JButton();
        jBut_Pop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLab_Tope = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTab_ColaDatos = new javax.swing.JTable();
        jBut_Insertar = new javax.swing.JButton();
        jBut_Eliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTab_DatoAleatorioCola = new javax.swing.JTable();
        jBut_DatoAleatorioCola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTab_DatoAleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Costo"
            }
        ));
        jScrollPane1.setViewportView(jTab_DatoAleatorio);

        jBut_DatoAleatorio.setText("Aleatorio");
        jBut_DatoAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_DatoAleatorioActionPerformed(evt);
            }
        });

        jTab_PilaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTab_PilaDatos);

        jBut_Push.setText("Push");
        jBut_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_PushActionPerformed(evt);
            }
        });

        jBut_Pop.setText("Pop");
        jBut_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_PopActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos:");

        jLab_Tope.setBackground(new java.awt.Color(0, 255, 255));
        jLab_Tope.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLab_Tope.setOpaque(true);

        jTab_ColaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTab_ColaDatos);

        jBut_Insertar.setText("Insertar");
        jBut_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InsertarActionPerformed(evt);
            }
        });

        jBut_Eliminar.setText("Eliminar");
        jBut_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EliminarActionPerformed(evt);
            }
        });

        jTab_DatoAleatorioCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Costo"
            }
        ));
        jScrollPane4.setViewportView(jTab_DatoAleatorioCola);

        jBut_DatoAleatorioCola.setText("Aleatorio");
        jBut_DatoAleatorioCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_DatoAleatorioColaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBut_DatoAleatorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBut_Push)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBut_Pop))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLab_Tope, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jBut_DatoAleatorioCola)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut_Insertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut_Eliminar)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut_DatoAleatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBut_Push)
                                    .addComponent(jBut_Pop))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLab_Tope, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBut_DatoAleatorioCola)
                            .addComponent(jBut_Insertar)
                            .addComponent(jBut_Eliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_DatoAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_DatoAleatorioActionPerformed
        oDato.aleatorio(jTab_DatoAleatorio);
    }//GEN-LAST:event_jBut_DatoAleatorioActionPerformed

    private void jBut_DatoAleatorioColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_DatoAleatorioColaActionPerformed
        oDato.aleatorio(jTab_DatoAleatorioCola);
    }//GEN-LAST:event_jBut_DatoAleatorioColaActionPerformed

    private void jBut_PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_PushActionPerformed
        try{
            int num = Integer.parseInt(this.jTab_DatoAleatorio.getValueAt(0, 0).toString());
            String nomb = this.jTab_DatoAleatorio.getValueAt(0, 1).toString();
            Double costo = Double.parseDouble(this.jTab_DatoAleatorio.getValueAt(0, 2).toString());

            Dato dato = new Dato(num,nomb,costo);

            pila.push(dato);
            this.mostrarPilaEnlazada(this.jTab_PilaDatos);
            this.jLab_Tope.setText(pila.getTamaño()+"");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jBut_PushActionPerformed

    private void jBut_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_PopActionPerformed
        pila.pop();
        this.mostrarPilaEnlazada(this.jTab_PilaDatos);
        this.jLab_Tope.setText(pila.getTamaño()+"");
    }//GEN-LAST:event_jBut_PopActionPerformed

    private void jBut_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InsertarActionPerformed
        try{
            int num = Integer.parseInt(this.jTab_DatoAleatorioCola.getValueAt(0, 0).toString());
            String nom = this.jTab_DatoAleatorioCola.getValueAt(0, 1).toString();
            double costo = Double.parseDouble(this.jTab_DatoAleatorioCola.getValueAt(0, 2).toString());

            Dato dato = new Dato(num,nom,costo);
            cola.insertar(dato);
            this.mostrarColaEnlazada(jTab_ColaDatos);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jBut_InsertarActionPerformed

    private void jBut_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EliminarActionPerformed
        cola.eliminar();
        this.mostrarColaEnlazada(jTab_ColaDatos);
    }//GEN-LAST:event_jBut_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_DatoAleatorio;
    private javax.swing.JButton jBut_DatoAleatorioCola;
    private javax.swing.JButton jBut_Eliminar;
    private javax.swing.JButton jBut_Insertar;
    private javax.swing.JButton jBut_Pop;
    private javax.swing.JButton jBut_Push;
    private javax.swing.JLabel jLab_Tope;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTab_ColaDatos;
    private javax.swing.JTable jTab_DatoAleatorio;
    private javax.swing.JTable jTab_DatoAleatorioCola;
    private javax.swing.JTable jTab_PilaDatos;
    // End of variables declaration//GEN-END:variables
}
